# Generated by Django 4.0.5 on 2022-06-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('flags', models.IntegerField(verbose_name='number of possible flags')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('avatar', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thmid', models.IntegerField(verbose_name='thm game id')),
                ('started_at', models.DateTimeField(verbose_name='start time')),
                ('finished_at', models.DateTimeField(verbose_name='finish time')),
                ('first_hacked', models.DateTimeField(verbose_name='first hacked time')),
                ('status', models.CharField(max_length=64)),
                ('game_type', models.CharField(max_length=64)),
                ('king_found', models.BooleanField(default=False)),
                ('king_changes', models.IntegerField(default=0)),
                ('resets', models.IntegerField(default=0)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koth.box')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='koth.player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='koth.player')),
            ],
        ),
    ]
