# Generated by Django 4.0.5 on 2022-06-28 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('flags', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('king', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koth.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koth.player')),
            ],
        ),
    ]
