# Generated by Django 4.0.5 on 2022-06-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koth', '0002_gameplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='game',
            name='thmid',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='creator_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
