# Generated by Django 4.0.5 on 2022-06-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koth', '0003_remove_game_creator_remove_game_thmid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='first_hacked',
            field=models.DateTimeField(null=True, verbose_name='first hacked time'),
        ),
    ]
