# Generated by Django 4.0.5 on 2022-06-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koth', '0004_alter_game_first_hacked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='finished_at',
            field=models.DateTimeField(null=True, verbose_name='finish time'),
        ),
    ]
