# Generated by Django 4.0.5 on 2022-07-22 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koth', '0005_alter_game_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='koth.GamePlayer', to='koth.player'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameplayers', to='koth.game'),
        ),
    ]
