apiVersion: batch/v1
kind: Job
metadata:
  name: db-reset
spec:
  template:
    spec:
      containers:
        - name: koth-api
          imagePullPolicy: IfNotPresent
          image: f11snipe/koth-api:updated
          command: ['/app/bin/db-reset']
          env:
            - name: DATABASE_NAME
              value: postgres

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: postgres

            - name: POSTGRES_NAME
              value: postgres

      restartPolicy: Never
  backoffLimit: 5