apiVersion: apps/v1
kind: Deployment
metadata:
  name: koth-api
  labels:
    app: koth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koth-api
  template:
    metadata:
      labels:
        app: koth-api
    spec:
      containers:
        - name: django-kube
          imagePullPolicy: IfNotPresent
          image: f11snipe/koth-api:updated
          command: ["python", "./src/manage.py", "runserver", "0.0.0.0:8000"]
          ports:
          - containerPort: 8000
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: SECRET_KEY
              value: "my-secret-key"

            - name: POSTGRES_NAME
              value: postgres

            - name: DATABASE_NAME
              value: postgres

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - mountPath: /app
              name: koth-api-local-src
      volumes:
      - name: koth-api-local-src
        hostPath:
          path: /usr/local/src/f11snipe/django-example-app
